In [1]:
import numpy as np
import pandas as pd

In [2]:
file_path = '/kaggle/input/cafe-sales-dirty-data-for-cleaning-training/dirty_cafe_sales.csv'
df = pd.read_csv(file_path)

data = df.copy()
data.head()

Transaction ID    Item Quantity Price Per Unit Total Spent  Payment Method  \
0    TXN_1961373  Coffee        2            2.0         4.0     Credit Card   
1    TXN_4977031    Cake        4            3.0        12.0            Cash   
2    TXN_4271903  Cookie        4            1.0       ERROR     Credit Card   
3    TXN_7034554   Salad        2            5.0        10.0         UNKNOWN   
4    TXN_3160411  Coffee        2            2.0         4.0  Digital Wallet   

   Location Transaction Date  
0  Takeaway       2023-09-08  
1  In-store       2023-05-16  
2  In-store       2023-07-19  
3   UNKNOWN       2023-04-27  
4  In-store       2023-06-11

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB


In [4]:
data.describe()

Transaction ID   Item Quantity Price Per Unit Total Spent  \
count           10000   9667     9862           9821        9827   
unique          10000     10        7              8          19   
top       TXN_1961373  Juice        5            3.0         6.0   
freq                1   1171     2013           2429         979   

        Payment Method  Location Transaction Date  
count             7421      6735             9841  
unique               5         4              367  
top     Digital Wallet  Takeaway          UNKNOWN  
freq              2291      3022              159

In [5]:
data.dtypes

Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object

In [6]:
# def fixIntFloat(x, kind):
#     if kind == 'int':
#         x = x.str.replace(r'[^0-9.]', '', regex=True)
#     else:
#         x = x.str.replace(r'[^0-9]', '', regex=True)
#     x = pd.to_numeric(x, errors='coerce')
#     return x

# def fixDateTime(col):
#     x = col
#     # x.unique()[:20] => some bs here, need to change that to ''
#     x = x.where(x.str.match(r'^\d{4}-\d{2}-\d{2}$'), None)
#     x = pd.to_datetime(x, errors='coerce')
#     return x

In [7]:
# temp_data = data.copy()
# temp_data['Quantity'] = fixIntFloat(temp_data['Quantity'], 'int')
# temp_data['Price Per Unit'] = fixIntFloat(temp_data['Price Per Unit'], 'float')
# temp_data['Total Spent'] = fixIntFloat(temp_data['Total Spent'], 'float')
# temp_data['Transaction Date'] = fixDateTime(temp_data['Transaction Date'])


In [8]:
temp_data = data.copy()

In [9]:
temp_data['Item'].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'UNKNOWN',
       'Sandwich', nan, 'ERROR', 'Juice', 'Tea'], dtype=object)

In [10]:
for col in temp_data:
    print(col, ':', temp_data[col].unique()[:20])

Transaction ID : ['TXN_1961373' 'TXN_4977031' 'TXN_4271903' 'TXN_7034554' 'TXN_3160411'
 'TXN_2602893' 'TXN_4433211' 'TXN_6699534' 'TXN_4717867' 'TXN_2064365'
 'TXN_2548360' 'TXN_3051279' 'TXN_7619095' 'TXN_9437049' 'TXN_8915701'
 'TXN_2847255' 'TXN_3765707' 'TXN_6769710' 'TXN_8876618' 'TXN_3709394']
Item : ['Coffee' 'Cake' 'Cookie' 'Salad' 'Smoothie' 'UNKNOWN' 'Sandwich' nan
 'ERROR' 'Juice' 'Tea']
Quantity : ['2' '4' '5' '3' '1' 'ERROR' 'UNKNOWN' nan]
Price Per Unit : ['2.0' '3.0' '1.0' '5.0' '4.0' '1.5' nan 'ERROR' 'UNKNOWN']
Total Spent : ['4.0' '12.0' 'ERROR' '10.0' '20.0' '9.0' '16.0' '15.0' '25.0' '8.0' '5.0'
 '3.0' '6.0' nan 'UNKNOWN' '2.0' '1.0' '7.5' '4.5' '1.5']
Payment Method : ['Credit Card' 'Cash' 'UNKNOWN' 'Digital Wallet' 'ERROR' nan]
Location : ['Takeaway' 'In-store' 'UNKNOWN' nan 'ERROR']
Transaction Date : ['2023-09-08' '2023-05-16' '2023-07-19' '2023-04-27' '2023-06-11'
 '2023-03-31' '2023-10-06' '2023-10-28' '2023-07-28' '2023-12-31'
 '2023-11-07' 'ERROR' '2023-05-

# EVERY COLUMN HAS GARBAGE VALUES:
**Strategy to fix them:**
* For categorical type, note down the types and replace the entries with nan which aren't in one of the types
* For numerical type, use regex to check for int or float type and replace any other with nan

In [11]:
items = ['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'Sandwich', 'Juice', 'Tea']

temp_data['Item'] = temp_data['Item'].where(temp_data['Item'].isin(items), np.nan)

In [12]:
items = ['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'Sandwich', 'Juice', 'Tea']
payment_method = ['Credit Card', 'Cash', 'Digital Wallet']
location = ['Takeaway', 'In-store']

In [13]:
# function for replacing garbage values for all categorical data
def replaceGarbage(column, correct):
    temp_data[column] = temp_data[column].where(temp_data[column].isin(correct), np.nan)

In [14]:
replaceGarbage('Item', items)
replaceGarbage('Payment Method', payment_method)
replaceGarbage('Location', location)

In [15]:
temp_data['Payment Method'].unique()

array(['Credit Card', 'Cash', nan, 'Digital Wallet'], dtype=object)

In [16]:
temp_data['Quantity'].str.replace(r'[^0-9]', '', regex=True)
temp_data['Quantity'] = pd.to_numeric(temp_data['Quantity'], errors='coerce')
temp_data['Quantity'].unique()

array([ 2.,  4.,  5.,  3.,  1., nan])

In [17]:
temp_data['Price Per Unit'].str.replace(r'[^0-9.]', '', regex=True)
temp_data['Price Per Unit'] = pd.to_numeric(temp_data['Price Per Unit'], errors='coerce')
temp_data['Price Per Unit'].unique()

array([2. , 3. , 1. , 5. , 4. , 1.5, nan])

In [18]:
temp_data['Total Spent'].str.replace(r'[^0-9.]', '', regex=True)
temp_data['Total Spent'] = pd.to_numeric(temp_data['Total Spent'], errors='coerce')
temp_data['Total Spent'].unique()[:20]

array([ 4. , 12. ,  nan, 10. , 20. ,  9. , 16. , 15. , 25. ,  8. ,  5. ,
        3. ,  6. ,  2. ,  1. ,  7.5,  4.5,  1.5])

In [19]:
temp_data['Transaction Date'] = temp_data['Transaction Date'].where(temp_data['Transaction Date'].str.match(r'^\d{4}-\d{2}-\d{2}$'), None)
temp_data['Transaction Date'] = pd.to_datetime(temp_data['Transaction Date'], errors='coerce')

In [20]:
temp_data.isnull().sum()

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

In [21]:
data.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

# Fill NULL Values


| Column           | Handling Missing Values                                   |
| ---------------- | --------------------------------------------------------- |
| Transaction ID   | Drop row if missing (essential unique identifier).        |
| Transaction Date | Forward/backward fill (time series continuity).           |
| Item             | Infer from `Price Per Unit`, else `'Unknown'`.            |
| Quantity         | Derive from `Total Spent ÷ Price`, else median.           |
| Price Per Unit   | Derive from `Total Spent ÷ Quantity`, else mean per Item. |
| Total Spent      | Derive from `Quantity × Price`, else median per Item.     |
| Payment Method   | Mode imputation, or `'Unknown'`.                          |
| Location         | `'Unknown'` if not inferable.                             |


### Transaction Date

Ways we can fill:
* sequential fill (ffill/bfill), but it assumes sorted dates
* fill with mode
* Dropna

In [22]:
temp_data = temp_data.dropna(subset=['Transaction Date'])
temp_data.isnull().sum()

Transaction ID         0
Item                 927
Quantity             454
Price Per Unit       506
Total Spent          476
Payment Method      3015
Location            3779
Transaction Date       0
dtype: int64

### Item
* Can be mapped with price per unit, coz unique
* or, impute with 'unknown'

In [23]:
price_map = temp_data.groupby('Item')['Price Per Unit'].mean().to_dict()
price_map

{'Cake': 3.0,
 'Coffee': 2.0,
 'Cookie': 1.0,
 'Juice': 3.0,
 'Salad': 5.0,
 'Sandwich': 4.0,
 'Smoothie': 4.0,
 'Tea': 1.5}

In [24]:
# reverse mapping
price_item = {price: item for item, price in price_map.items()}
price_item

{3.0: 'Juice',
 2.0: 'Coffee',
 1.0: 'Cookie',
 5.0: 'Salad',
 4.0: 'Smoothie',
 1.5: 'Tea'}

In [25]:
temp_data['Item'] = temp_data['Item'].fillna(temp_data['Price Per Unit'].map(price_item))
temp_data['Item'].isnull().sum()

51

In [26]:
temp_data['Price Per Unit'] = temp_data['Price Per Unit'].fillna(temp_data['Total Spent']/ temp_data['Quantity'])
temp_data['Quantity'] = temp_data['Quantity'].fillna(temp_data['Total Spent']/ temp_data['Price Per Unit'])
temp_data['Total Spent'] = temp_data['Total Spent'].fillna(temp_data['Price Per Unit']* temp_data['Quantity'])
temp_data.isnull().sum()

Transaction ID         0
Item                  51
Quantity              36
Price Per Unit        35
Total Spent           39
Payment Method      3015
Location            3779
Transaction Date       0
dtype: int64

In [27]:
temp_data['Item'] = temp_data['Item'].fillna(temp_data['Price Per Unit'].map(price_item))
temp_data.isnull().sum()

Transaction ID         0
Item                   6
Quantity              36
Price Per Unit        35
Total Spent           39
Payment Method      3015
Location            3779
Transaction Date       0
dtype: int64

In [28]:
temp_data['Price Per Unit'] = temp_data['Price Per Unit'].fillna(temp_data['Item'].map(price_map))
temp_data.isnull().sum()

Transaction ID         0
Item                   6
Quantity              36
Price Per Unit         6
Total Spent           39
Payment Method      3015
Location            3779
Transaction Date       0
dtype: int64

In [29]:
temp_data['Quantity'] = temp_data['Quantity'].fillna(temp_data['Quantity'].median())
temp_data.isnull().sum()

Transaction ID         0
Item                   6
Quantity               0
Price Per Unit         6
Total Spent           39
Payment Method      3015
Location            3779
Transaction Date       0
dtype: int64

In [30]:
temp_data = temp_data.dropna(subset=['Item'])
temp_data['Total Spent'] = temp_data['Total Spent'].fillna(temp_data['Quantity']*temp_data['Price Per Unit'])
temp_data.isnull().sum()

Transaction ID         0
Item                   0
Quantity               0
Price Per Unit         0
Total Spent            0
Payment Method      3012
Location            3776
Transaction Date       0
dtype: int64

In [31]:
temp_data['Location'].value_counts()

Location
Takeaway    2889
In-store    2869
Name: count, dtype: int64

In [32]:
temp_data['Location'] = temp_data['Location'].fillna('Unknown')
temp_data['Location'].value_counts()

Location
Unknown     3776
Takeaway    2889
In-store    2869
Name: count, dtype: int64

In [33]:
temp_data['Payment Method'].value_counts()

Payment Method
Digital Wallet    2196
Credit Card       2168
Cash              2158
Name: count, dtype: int64

In [34]:
temp_data['Payment Method'] = temp_data['Payment Method'].fillna('Unknown')
temp_data.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [35]:
temp_data.head()

Transaction ID    Item  Quantity  Price Per Unit  Total Spent  \
0    TXN_1961373  Coffee       2.0             2.0          4.0   
1    TXN_4977031    Cake       4.0             3.0         12.0   
2    TXN_4271903  Cookie       4.0             1.0          4.0   
3    TXN_7034554   Salad       2.0             5.0         10.0   
4    TXN_3160411  Coffee       2.0             2.0          4.0   

   Payment Method  Location Transaction Date  
0     Credit Card  Takeaway       2023-09-08  
1            Cash  In-store       2023-05-16  
2     Credit Card  In-store       2023-07-19  
3         Unknown   Unknown       2023-04-27  
4  Digital Wallet  In-store       2023-06-11

In [36]:
temp_data.to_csv('/kaggle/working/cafe-sales-clean.csv', index=False)